import sql from "../../../store/database.js";

// ── Add individual venta (backward compat) ───────────────────
export async function add({ nombre, precio, product_id, cantidad, fecha_cobro }) {
  return await sql.begin(async (sql) => {
    // 0. Obtener el costo del producto
    const [producto] = await sql`
            SELECT precio FROM productos WHERE id = ${product_id}
        `;

    const costo_total = Number(producto.precio) * Number(cantidad);
    const ganancia = Number(precio) - costo_total;

    // 1. Registrar la venta
    const [venta] = await sql`
            INSERT INTO ventas (nombre, precio, producto_id, cantidad, ganancia, fecha_cobro)
            VALUES (${nombre}, ${precio}, ${product_id}, ${cantidad}, ${ganancia}, ${fecha_cobro || null})
            RETURNING id
        `;

    // 2. Restar valor del Total Invertido (Stock físico)
    await sql`
            UPDATE productos 
            SET stock = stock - ${cantidad}
            WHERE id = ${product_id}
        `;

    return venta;
  });
}

// ── Add factura (multi-product, single transaction) ─────────
// items: [{ product_id, cantidad, precio }]
// factura_id: string (UUID generated by frontend)
// fecha_cobro: optional date string
export async function addFactura({ items, factura_id, fecha_cobro }) {
  return await sql.begin(async (sql) => {
    const inserted = [];

    for (const item of items) {
      const { product_id, cantidad, precio } = item;

      // 1. Get product cost
      const [producto] = await sql`
        SELECT nombre, precio FROM productos WHERE id = ${product_id}
      `;

      const costo_total = Number(producto.precio) * Number(cantidad);
      const ganancia = Number(precio) - costo_total;

      // 2. Insert venta row
      const [venta] = await sql`
        INSERT INTO ventas (nombre, precio, producto_id, cantidad, ganancia, factura_id, fecha_cobro)
        VALUES (${producto.nombre}, ${precio}, ${product_id}, ${cantidad}, ${ganancia}, ${factura_id}, ${fecha_cobro || null})
        RETURNING id
      `;

      // 3. Deduct stock
      await sql`
        UPDATE productos SET stock = stock - ${cantidad} WHERE id = ${product_id}
      `;

      inserted.push(venta);
    }

    return inserted;
  });
}

// ── List grouped by factura_id ──────────────────────────────
// Ventas viejas (sin factura_id) se agrupan como si cada una fuera su propia factura.
export async function listGrouped() {
  const rows = await sql`
    SELECT
      COALESCE(factura_id, 'legacy-' || id) AS factura_id,
      MIN(fecha_cobro) AS fecha_cobro,
      MIN(created_at) AS fecha,
      SUM(cantidad) AS cantidad,
      SUM(precio) AS precio,
      SUM(ganancia) AS ganancia,
      json_agg(json_build_object(
        'nombre', nombre,
        'cantidad', cantidad,
        'precio', precio
      )) AS productos
    FROM ventas
    GROUP BY COALESCE(factura_id, 'legacy-' || id)
    ORDER BY MIN(created_at) DESC
  `;
  return rows;
}

// ── List all (flat, for backward compat) ────────────────────
export async function list() {
  const list = await sql`SELECT id, nombre, precio, producto_id, cantidad, ganancia, fecha_cobro, created_at AS fecha FROM ventas ORDER BY created_at DESC, id DESC`;
  return list;
}

export async function update({ id, nombre, precio, product_id }) {
  await sql`UPDATE ventas SET nombre=${nombre}, precio=${precio},producto_id=${product_id} WHERE id = ${id}`;
}

export async function remove({ id }) {
  await sql`DELETE FROM ventas WHERE id=${id}`;
}
